language: java
jdk: oraclejdk8
sudo: false

cache:
    directories:
        - $HOME/.m2

before_script:
    - chmod +x gradlew

script:
    - ./gradlew build jacocoTestReport

after_success:
    - bash <(curl -s https://codecov.io/bash)